export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUECCESS = "FETCH_COUNTRIES_SUECCESS";
export const FETCH_COUNTRIES_FAILED = "FETCH_COUNTRIES_FAILED";

export const CLEAR_DISPLAY_FILTERS = "CLEAR_DISPLAYED_FILTERS";
export const FILTER_DISPLAYED_COUNTRIES = "FILTER_DISPLAYED_COUNTRIES";
